
log_dir: "logs/test"
seed: 7354
pretrained_model: ""
batch_size: 64
max_epochs: 10000
ckpt_period: 25
val_period: 10
use_amp: false
device: "gpu"
n_gpus: 1
n_tpus: 0

use_profiler: false

dataset:
  load_from_disk: true
  training_list: "filelists/jsut_jsss_train.txt"
  validation_list: "filelists/jsut_jsss_val.txt"
  n_bins: 128
  # WaveRNN requires hop_length == n_bins
  hop_length: 128
  n_frames: 160
  sr: 24000
  num_workers: 2
  pin_memory: false



model:
  # dim_in_d: 128
  freq_channels: 128
  trunk_channels: 256
  
  n_resblk_g: 7

  noise_sigma_d: 0.01
  n_resblk_d: 6

critic:
  hinge_offset: 0.5
  lambda_cyc: 10
  lambda_id: 1

optimizer:
  lr: 2.0e-4