[tool.poetry]
name = "scyclonepytorch"
version = "0.1.0"
description = "Reimplementation of Scyclone with PyTorch"
authors = ["Tarepan"]
readme = "README.md"
repository = "https://github.com/tarepan/Scyclone-PyTorch"

[tool.poetry.dependencies]
python = "^3.6.1"
torch = "^1.6.0"
pytorch-lightning = "^0.10.0"
npvcc2016 = "^1.0.8"
torchaudio = "^0.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
