[tool.poetry]
name = "scyclonepytorch"
version = "0.1.0"
description = "Reproduction of \"Scyclone\" with PyTorch"
authors = ["Tarepan"]

[tool.poetry.dependencies]
python = "^3.6.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
